import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("room_dataset.csv")
print(data.head())
plt.figure(figsize=(8, 6))
plt.hist(data['S1_Light'])
plt.xlabel('Light (Lux)')
plt.ylabel('Room Count')
plt.title('Distribution of Light Levels (S1_Light)')
plt.show()
print("2. Distribution of light levels graph displayed.")

plt.figure(figsize=(8, 6))
plt.hist(data['S2_Light'])
plt.xlabel('Light (Lux)')
plt.ylabel('Room Count')
plt.title('Distribution of Light Levels (S2_Light)')
plt.show()
print("2. Distribution of light levels graph displayed.")

plt.figure(figsize=(8, 6))
plt.hist(data['S3_Light'])
plt.xlabel('Light (Lux)')
plt.ylabel('Room Count')
plt.title('Distribution of Light Levels (S3_Light)')
plt.show()
print("2. Distribution of light levels graph displayed.")

plt.figure(figsize=(8, 6))
plt.hist(data['S4_Light'])
plt.xlabel('Light (Lux)')
plt.ylabel('Room Count')
plt.title('Distribution of Light Levels (S4_Light)')
plt.show()
print("2. Distribution of light levels graph displayed.")