import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("room_dataset.csv")
print(data.head())
fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(12, 8))
axes[0, 0].bar(data['Time'], data['S1_Temp'], color='steelblue')
axes[0, 0].set_xlabel('Time')
axes[0, 0].set_ylabel('Temperature (Celsius)')
axes[0, 0].set_title('Temperature Variation in Room 1')
axes[0, 1].bar(data['Time'], data['S2_Temp'], color='steelblue')
axes[0, 1].set_xlabel('Time')
axes[0, 1].set_ylabel('Temperature (Celsius)')
axes[0, 1].set_title('Temperature Variation in Room 2')
axes[1, 0].bar(data['Time'], data['S3_Temp'], color='steelblue')
axes[1, 0].set_xlabel('Time')
axes[1, 0].set_ylabel('Temperature (Celsius)')
axes[1, 0].set_title('Temperature Variation in Room 3')
axes[1, 1].bar(data['Time'], data['S4_Temp'], color='steelblue')
axes[1, 1].set_xlabel('Time')
axes[1, 1].set_ylabel('Temperature (Celsius)')
axes[1, 1].set_title('Temperature Variation in Room 4')
plt.tight_layout()
plt.show()
